version: '3.9'

services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2-java11
    restart: always
    user: root
    ports:
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=10
      - SPARK_WORKER_MEMORY=10G
      - SPARK_DRIVER_MEMORY=10G
      - SPARK_EXECUTOR_MEMORY=10G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
    networks:
      - overlay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "16"
          memory: 20G
        reservations:
          cpus: "10"
          memory: 10G

  spark-history-server:
    image: bde2020/spark-history-server:3.1.1-hadoop3.2-java11
    restart: always
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - history_volume:/tmp/spark-events
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  history_volume:

networks:
  overlay:
    external: true
    name: story-network
