version: '3.9'

services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2-java11
    restart: always
    user: root
    ports:
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_PUBLIC_DNS=spark.story.samssh.ir
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  spark-worker1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_PUBLIC_DNS=spark.story.samssh.ir
    networks:
      - overlay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "3"
          memory: 3G

  spark-worker2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8082
      - SPARK_PUBLIC_DNS=spark.story.samssh.ir
    networks:
      - overlay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "3"
          memory: 3G

  spark-worker3:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8083
      - SPARK_PUBLIC_DNS=spark.story.samssh.ir
    networks:
      - overlay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "3"
          memory: 3G

  spark-history-server:
    image: bde2020/spark-history-server:3.1.1-hadoop3.2-java11
    restart: always
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - history_volume:/tmp/spark-events
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  history_volume:

networks:
  overlay:
    external: true
    name: story-network
