version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    hostname: spark_master
    user: root
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
    volumes:
      - master_vol:/spark/master
    networks:
      - story-network

  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    hostname: spark_worker_1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_LOCAL_IP=0.0.0.0
    volumes:
      - worker1_vol:/spark/w1
    networks:
        - story-network

  spark-worker-2:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-2
    hostname: spark_worker_2

    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_LOCAL_IP=0.0.0.0
    volumes:
      - worker2_vol:/spark/w2
    networks:
        - story-network

  spark-worker-3:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-3
    hostname: spark_worker_3

    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_LOCAL_IP=0.0.0.0
    volumes:
      - worker3_vol:/spark/w3
    networks:
        - story-network

  spark-history-server:
      image: bde2020/spark-history-server:3.2.0-hadoop3.2
      container_name: spark-history-server
      depends_on:
        - spark-master
      ports:
        - "18081:18081"
      volumes:
        - ./tmp/spark-events-local:/tmp/spark-events
        - history_vol:/spark/history
      networks:
        - story-network

volumes:
  master_vol:
  worker1_vol:
  worker2_vol:
  worker3_vol:
  history_vol:
  
networks:
    story-network:
      external: true
