version: '3.9'

services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2-java11
    user: root
    ports:
      - "8080:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_LOCAL_IP=0.0.0.0
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G


  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_LOCAL_IP=0.0.0.0
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

  spark-worker-3:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_WORKER_PORT=8081
      - SPARK_LOCAL_IP=0.0.0.0
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

  spark-history-server:
    image: bde2020/spark-history-server:3.1.1-hadoop3.2-java11
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - history_vol:/tmp/spark-events
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  history_volume:

networks:
  overlay:
    external: true
    name: story-network
