version: "3.9"

services:
  name-node:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    # restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_name_node:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME="story cluster"
    env_file:
      - ./hadoop.env
    networks:
      - overlay

  data-node1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # restart: always
    depends_on:
      - name-node
    volumes:
      - hadoop_data_node1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "name-node:9870"
    env_file:
      - ./hadoop.env
    networks:
      - overlay

  data-node2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # restart: always
    depends_on:
      - name-node
    volumes:
      - hadoop_data_node2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "name-node:9870"
    env_file:
      - ./hadoop.env
    networks:
      - overlay
  
  resource-manager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    restart: always
    depends_on:
      - data-node1
      - data-node2
    environment:
      SERVICE_PRECONDITION: "name-node:9000 name-node:9870 data-node1:9864 data-node2:9864"
    env_file:
      - ./hadoop.env
    networks:
      - overlay

  node-manager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    # restart: always
    depends_on:
      - resource-manager
    environment:
      SERVICE_PRECONDITION: "name-node:9000 name-node:9870 data-node1:9864 data-node2:9864 resource-manager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - overlay

  history-server:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    # restart: always
    depends_on:
      - resource-manager
    environment:
      SERVICE_PRECONDITION: "name-node:9000 name-node:9870 data-node1:9864 data-node2:9864 resource-manager:8088"
    volumes:
      - hadoop_history_server:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - overlay
  
volumes:
  hadoop_name_node:
  hadoop_data_node1:
  hadoop_data_node2:
  hadoop_history_server:

networks:
    overlay:
      external: true
      name: story-network
