version: '3.9'

services:

  cassandra1:
    image: cassandra:3.11.13
    restart: always
    volumes:
      - cassandra_volume1:/var/lib/cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2"
      - "CASSANDRA_CLUSTER_NAME=Story Cluster"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "HEAP_NEWSIZE=128M"
      - "MAX_HEAP_SIZE=3072M"
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 3G

  cassandra2:
    image: cassandra:3.11.13
    restart: always
    volumes:
      - cassandra_volume2:/var/lib/cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2"
      - "CASSANDRA_CLUSTER_NAME=Story Cluster"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "HEAP_NEWSIZE=128M"
      - "MAX_HEAP_SIZE=3072M"
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 3G

  cassandra3:
    image: cassandra:3.11.13
    restart: always
    volumes:
      - cassandra_volume3:/var/lib/cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2"
      - "CASSANDRA_CLUSTER_NAME=Story Cluster"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "HEAP_NEWSIZE=128M"
      - "MAX_HEAP_SIZE=3072M"
    depends_on:
      - cassandra1
      - cassandra2
    links:
      - cassandra1
      - cassandra2
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 3G

  loadbalancer:
    hostname: cassandra-cluster
    image: haproxy:2.5
    restart: always
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    links:
      - cassandra1
      - cassandra2
      - cassandra3
    networks:
      - overlay
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

  cassandra-web:
    image: ipushc/cassandra-web
    restart: always
    ports:
      - "3000:8083"
    environment:
      - "CASSANDRA_HOST=cassandra-cluster"
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  cassandra_volume1:
  cassandra_volume2:
  cassandra_volume3:

networks:
  overlay:
    external: true
    name: story-network
