version: '3.9'

services:

  zookeeper1:
    image: bitnami/zookeeper:3.7.1
    restart: always
    volumes:
      - zookeeper_volume1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
#      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ZOO_SERVERS=zookeeper1:2888:3888
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

#  zookeeper2:
#    image: bitnami/zookeeper:3.7.1
#    restart: always
#    volumes:
#      - zookeeper_volume2:/bitnami/zookeeper
#    environment:
#      - ZOO_SERVER_ID=2
#      - ALLOW_ANONYMOUS_LOGIN=yes
#      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
#    networks:
#      - overlay
#    deploy:
#      resources:
#        limits:
#          cpus: "0.50"
#          memory: 512M
#        reservations:
#          cpus: "0.25"
#          memory: 128M
#
#  zookeeper3:
#    image: bitnami/zookeeper:3.7.1
#    restart: always
#    volumes:
#      - zookeeper_volume3:/bitnami/zookeeper
#    environment:
#      - ZOO_SERVER_ID=3
#      - ALLOW_ANONYMOUS_LOGIN=yes
#      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
#    networks:
#      - overlay
#    deploy:
#      resources:
#        limits:
#          cpus: "0.50"
#          memory: 512M
#        reservations:
#          cpus: "0.25"
#          memory: 128M

  kafka1:
    image: bitnami/kafka:3.2.1
    restart: always
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_HEAP_OPTS="-Xmx1024m -Xms256m"
    depends_on:
      - zookeeper1
#      - zookeeper2
#      - zookeeper3
    links:
      - zookeeper1
#      - zookeeper2
#      - zookeeper3
    volumes:
      - kafka_volume1:/bitnami/kafka
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G

#  kafka2:
#    image: bitnami/kafka:3.2.1
#    restart: always
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#    depends_on:
#      - zookeeper1
#      - zookeeper2
#      - zookeeper3
#    links:
#      - zookeeper1
#      - zookeeper2
#      - zookeeper3
#    volumes:
#      - kafka_volume2:/bitnami/kafka
#    networks:
#      - overlay
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: 4G
#        reservations:
#          cpus: "0.5"
#          memory: 1G
#
#  kafka3:
#    image: bitnami/kafka:3.2.1
#    restart: always
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#    depends_on:
#      - zookeeper1
#      - zookeeper2
#      - zookeeper3
#    links:
#      - zookeeper1
#      - zookeeper2
#      - zookeeper3
#    volumes:
#      - kafka_volume3:/bitnami/kafka
#    networks:
#      - overlay
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: 4G
#        reservations:
#          cpus: "0.5"
#          memory: 1G

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - "9010:9010"
    environment:
      SERVER_PORT: "9010"
      KAFKA_BROKERCONNECT: "kafka1:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka1
#      - kafka2
#      - kafka3
    networks:
      - overlay
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  zookeeper_volume1:
  zookeeper_volume2:
  zookeeper_volume3:
  kafka_volume1:
  kafka_volume2:
  kafka_volume3:

networks:
  overlay:
    external: true
    name: story-network
