version: '3'
services:
  zookeeper1:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - '2181:2181'
      - '6001:2888'
      - '6051:3888'
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - story-network

  zookeeper2:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper2
    hostname: zookeeper2
    ports:
      - '2182:2181'
      - '6002:2888'
      - '6052:3888'
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - story-network

  zookeeper3:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper3
    hostname: zookeeper3
    ports:
      - '2183:2181'
      - '6003:2888'
      - '6053:3888'
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    networks:
      - story-network

  kafka1:
    image: 'bitnami/kafka:3.1'
    container_name: kafka1
    hostname: kafka1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      # - KAFKA_CREATE_TOPICS="topic1:5:1,topic2:5:1"
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - kafka_vol1:/kafka/brocker1
    networks:
      - story-network

  kafka2:
    image: 'bitnami/kafka:3.1'
    container_name: kafka2
    hostname: kafka2
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      # - KAFKA_CREATE_TOPICS="topic1:5:1,topic2:5:1"
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - kafka_vol2:/kafka/brocker2
    networks:
      - story-network

  kafka3:
    image: 'bitnami/kafka:3.1'
    container_name: kafka3
    hostname: kafka3
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      # - KAFKA_CREATE_TOPICS="topic1:5:1,topic2:5:1"
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - kafka_vol3:/kafka/brocker3
    networks:
      - story-network
        
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9010:9010"
    environment:
      SERVER_PORT: "9010"
      KAFKA_BROKERCONNECT: "kafka1:9092,kafka2:9092,kafka3:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"
    networks:
      - story-network

volumes:
  kafka_vol1:
  kafka_vol2:
  kafka_vol3:

networks:
    story-network:
      external: true